const IPHONE_X_HOME_INDICATOR_PADDING = 34;
const IPHONE_X_LONG_SIDE = 812;
const IPHONE_X_NOTCH_PADDING = 30;

const IPHONE_XR_LONG_SIDE = 896;
const IPHONE_XR_NOTCH_PADDING = 34;

const IPHONE_12_LONG_SIDE = 844;
const IPHONE_12_MAX_LONG_SIDE = 926;

const NAVIGATION_HEADER_HEIGHT = 64;

module.exports = {
  IPHONE_X_HOME_INDICATOR_PADDING,
  IPHONE_X_LONG_SIDE,
  IPHONE_X_NOTCH_PADDING,
  IPHONE_XR_LONG_SIDE,
  IPHONE_XR_NOTCH_PADDING,
  IPHONE_12_LONG_SIDE,
  IPHONE_12_MAX_LONG_SIDE,
  NAVIGATION_HEADER_HEIGHT,
}
