const { Platform, StatusBar } = require('react-native');
const {
  NAVIGATION_BAR_HEIGHT,
  IPHONE_X_HOME_INDICATOR_PADDING,
  IPHONE_X_LONG_SIDE,
  IPHONE_X_NOTCH_PADDING,
  IPHONE_XR_LONG_SIDE,
  IPHONE_12_LONG_SIDE,
  IPHONE_12_MAX_LONG_SIDE,
  NAVIGATION_HEADER_HEIGHT,
  IPHONE_XR_NOTCH_PADDING,
} = require('./helpers');

const STATUS_BAR_OFFSET =
  Platform.OS === 'android' ? -StatusBar.currentHeight : 0;

module.exports = {
  IPHONE_X_HOME_INDICATOR_PADDING,
  IPHONE_X_LONG_SIDE,
  IPHONE_X_NOTCH_PADDING,
  IPHONE_XR_LONG_SIDE,
  IPHONE_XR_NOTCH_PADDING,
  IPHONE_12_LONG_SIDE,
  IPHONE_12_MAX_LONG_SIDE,
  NAVIGATION_BAR_HEIGHT,
  NAVIGATION_HEADER_HEIGHT,
  STATUS_BAR_OFFSET,
};
